### ISSUE TITLE
Papra PCB engineering drawing 

### ISSUE THREAD

**Issue by mmroden** [tetrabiodistributed/PAPRA-PCB#15]
Please submit an engineering diagram in PDF, PNG, whatever makes sense.

Bonus points for a soldering jig.

**Comment by darraghbr** [comment]
[A-TET- Papra Control PCBA Drawing.pdf](https://github.com/tetrabiodistributed/PAPRA-PCB/files/5961311/A-TET-.Papra.Control.PCBA.Drawing.pdf)

@mechatroniks-git Please review when able.

**Comment by mechatroniks-git** [comment]
Looks nice. A few comments:
1. The board, as it comes from JLC should have the fuse installed, no need to point that out.
2. The PCB should have a balloon
3. Washers & Nuts included with the potentiometer and DC jacks - not sure if they should be separate line items?
4. Lightpipe is already on the M12 controller BOM? It should only be on 1 BOM, probably the other one, as it needs to be assembled with the board, after the board is installed.

![image](https://user-images.githubusercontent.com/57600622/107706358-096c5480-6c75-11eb-8d27-0d0a6c7d1aaa.png)

**Comment by darraghbr** [comment]
Please see attached, I believe I have dealt with all of your comments. 

Aside from the nuts and washers appearing on the BOM, Because they are seperate components there isn't a nice way to not have them visible on the BOM and also have them visible on the drawing. I can remove them from the drawing and BOM if desired. 

[D-TET-.Papra.PCBA.Drawing.pdf](https://github.com/tetrabiodistributed/PAPRA-PCB/files/5968976/D-TET-.Papra.PCBA.Drawing.pdf)

**Comment by mechatroniks-git** [comment]
LGTM

**Comment by darraghbr** [comment]
@mmroden please review when able.

**Comment by mmroden** [comment]
Man, this is _phenomenal_!
